server:
    port: 8686
    context-path: #/

logging:
    level:
        tk.mybatis: DEBUG
        
spring:
   datasource:
      initialize: false
   redis:
   	  database:
   	  host:
   	  password:
   	  port: 6888
   	  pool:
   	    max-idle: 8
   	    min-idle: 0
   	    max-active: 8
   	    max-wait: -1
# 	  sentinel:
# 	  	master: 
# 	  	nodes: 

mvc:
   view:
       prefix: /templates/
       suffix: .ftl
       

freemarker:
  cache: false
  request-context-attribute: request

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: com.fpx.xinyou.util.MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: com.fpx.xinyou.model
#    mapperScanner:
#        basePackage: com.fpx.xinyou.mapper


oprt:
    datasource:
        name: oprtDs
        url: jdbc:oracle:thin:@172.16.30.26:1521:fz
        username: oprt
        password: oprt
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 10
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
ctr:
    datasource:
        name: oprtDs
        url: jdbc:oracle:thin:@172.16.30.26:1521:fz
        username: ctr
        password: ctr
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 3
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 3
 
base:
    datasource:
        name: baseDs
        url: jdbc:oracle:thin:@172.16.30.26:1521:fz
        username: messager
        password: messager
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        


mymq:
   address: 172.16.30.50:5672
   user: lz
   password: 0